### ISSUE TITLE
#US17 Página Acerca de/quienes somos

### ISSUE THREAD

**Issue by MonicaAntich** [Desarrollo-Web-2024-segundo-intento/Proyecto-Integrador-II#10]
Continuar y mejorar Acerca de

**Comment by Jesica-A** [comment]
### HISTORIA DE USUARIO:
Como usuario quiero visualizar una pagina de “Acerca de” con información para conocer al equipo a quien le voy a brindar mis datos

### CRITERIO DE ACEPTACION:
1.	La página debe la barra de navegación y footer
2.	Visualizar una página con información básica

### TASKS:
- [x] Diseñar
- [x] Escribir HTML
- [x] Diseño Responsive (CSS/Bootstrap)
- [x] Testear
