### ISSUE TITLE
#US21 Página de Turnos

### ISSUE THREAD

**Issue by MonicaAntich** [Desarrollo-Web-2024-segundo-intento/Proyecto-Integrador-II#6]
Continuar y mejorar turnos

**Comment by Jesica-A** [comment]
### HISTORIA DE USUARIO:
Como usuario quiero visualizar una pagina de turnos para poder elegir especialidad, medico y posteriormente los horarios y pagos.

### CRITERIOS DE ACEPTACION:
1. Pagina con especialidad disponibles
2. Cada especialidad mostrara en detalle los medicos disponibles
3. Al seleccionar uin medico inidicara sus horarios disponibles
4. Dentro de esta pagina se podra agendar un turno medico

### TASKS:
- [x] Diseñar
- [x] Escribir HTML
- [x] Diseño Responsive (CSS/Boostrap)
- [x] Pagina interactiva con Javascript
- [x] Testear
