### ISSUE TITLE
#US20 Pagina Perfil de Paciente

### ISSUE THREAD

**Issue by MonicaAntich** [Desarrollo-Web-2024-segundo-intento/Proyecto-Integrador-II#7]
Continuar y mejorar paciente

**Comment by Jesica-A** [comment]
### HISTORIA DE USUARIO
Como usuario quiero visualizar mi Perfil con mi informacion

### CRITERIOS DE ACEPTACION
1. El usuario registrado y logueado puede ver una seccion llamada "Perfil"
2. El Perfil deberá contener la siguiente informacion:
- Nombre 
- Apellido
- Domicilio
- DNI
- Telefono
- Email
- Contraseña
3. Se visualizará una seccion "Historial de turnos" donde estaran todos los turnos (pasados, en el dia actual y futuros agendados)
4. Se visualirará una seccion "Historial clinico" con resultados de diagnosticos medicos/examenes clinicos

### TASKS:
- [ ] Diseñar
- [ ] Escribir HTML
- [ ] Diseño Responsive (CSS/Bootstrap)
- [ ] Conexion con base de datos
- [ ] Testear
