### ISSUE TITLE
#US18 Página Contacto

### ISSUE THREAD

**Issue by MonicaAntich** [Desarrollo-Web-2024-segundo-intento/Proyecto-Integrador-II#8]
Continuar y mejorar contacto

**Comment by Jesica-A** [comment]
### HISTORIA DE USUARIO:
Como usuario quiero visualizar una página de contacto con un formulario para tener un medio de contacto con el sistema 

### CRITERIOS DE ACEPTACION:
1.	La página debe la barra de navegación y footer.
2.	El formulario deberá tener los siguientes campos:
•	Nombre y Apellido
•	Email
•	Mensaje
•	Botón de “Enviar”
3.	El formulario deberá tener validaciones en los campos:
•	Nombre y apellido: acepta solo caracteres alfabéticos
•	Email: validar el formato aaaa@aaa.com. 
•	Mensaje: validar que el campo no esté vacío.
•	Botón enviar: solo enviará el formulario cuando todos los campos estén completos

### TASKS:
- [x] Diseñar
- [x] Escribir HTML
- [x] Diseño Responsive (CSS/Bootstrap)
- [x] Validaciones con Javascript
- [x] Testear
