### ISSUE TITLE
#US16 Página de inicio

### ISSUE THREAD

**Issue by MonicaAntich** [Desarrollo-Web-2024-segundo-intento/Proyecto-Integrador-II#9]
Continuar y mejorar index con el navbar

**Comment by Jesica-A** [comment]
### HISTORIA DE USUARIO:
Como usuario quiero visualizar una página de inicio con información del sistema para conocer el sistema

### CRITERIOS DE ACEPTACION:
1.	La página debe la barra de navegación y footer.
2.	Visualizar información relevante sobre el sistema

### TASKS:
- [x] Diseñar
- [x] Escribir HTML
- [x] Diseño responsive (CSS/Bootstrap)
- [x] Testear
